"use client";

import React from "react";

// Components
import { Inter } from "next/font/google";
import { GlobalStyled } from "../GlobalStyled";

// React Query
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "@/shared/libs/query";

// Layouts
import AntdRegistry from "../AntdRegistry";
import AntdTheme from "../AntdTheme";
import StyledRegistry from "../StyledRegistry";
import StyledTheme from "../StyledTheme";

// Font connection
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <AntdRegistry>
        <AntdTheme>
          <StyledRegistry>
            <StyledTheme>
              <GlobalStyled>
                <QueryClientProvider client={queryClient}>
                  {children}
                </QueryClientProvider>
              </GlobalStyled>
            </StyledTheme>
          </StyledRegistry>
        </AntdTheme>
      </AntdRegistry>
    </body>
  </html>
);

export default RootLayout;
