"use client";

import React from "react";

// Styles
import "antd/dist/reset.css";

// React Query
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "@/shared/libs/query";

// Fonts
import { inter } from "@/shared/styles/fonts";

// Layouts
import AntdRegistry from "../AntdRegistry";
import StyledRegistry from "../StyledRegistry";
import Theme from "@/shared/ui/Theme";
import GlobalStyled from "@/shared/ui/GlobalStyled";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <StyledRegistry>
            <QueryClientProvider client={queryClient}>
              <Theme>
                <GlobalStyled>{children}</GlobalStyled>
              </Theme>
            </QueryClientProvider>
          </StyledRegistry>
        </AntdRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
